<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>myparser-provider-douyin</AssemblyName>
        <RootNamespace>MyParser.Provider.Douyin</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\RiderProjects\ShiroBot\ShiroBot.AvaloniaSdk\ShiroBot.AvaloniaSdk.csproj" />
        <ProjectReference Include="..\..\..\..\RiderProjects\ShiroBot\ShiroBot.Qq.Model\ShiroBot.Qq.Model.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MyParser.Sharing\MyParser.Sharing.csproj" />
        <Compile Include="..\MyParser\SdkModelAliases.cs" Link="SdkModelAliases.cs" />
        <Compile Include="..\MyParser\SdkMessageAdapters.cs" Link="SdkMessageAdapters.cs" />
    </ItemGroup>

</Project>
