<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="VideoLibrary" Version="3.3.1" />
    <PackageVersion Include="ShiroBot.SDK" Version="0.9.3" />
    <PackageVersion Include="SilkCodec.NET" Version="1.2.0" />
    <PackageVersion Include="LightDl" Version="0.4.3" />
  </ItemGroup>
</Project>
