<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Net.Codecrete.QrCodeGenerator" Version="3.0.0" />
    <PackageVersion Include="LightDl" Version="0.3.0" />
    <PackageVersion Include="NLayer" Version="2.0.1" />
    <PackageVersion Include="SharpMP4" Version="0.3.1" />
    <PackageVersion Include="SilkCodec.NET" Version="1.0.1" />
  </ItemGroup>
</Project>
