<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>myparser-sharing</AssemblyName>
        <RootNamespace>Shirobot.Plugin.MyParser</RootNamespace>
    </PropertyGroup>

    <Import Project="$(ShiroBotSourceRoot)\SDK\buildTransitive\ShiroBot.SDK.props"
            Condition="'$(UseShiroBotSource)' == 'true'" />

    <ItemGroup>
        <ProjectReference Include="$(ShiroBotSourceRoot)\SDK\ShiroBot.SDK.csproj"
                          Private="false"
                          Condition="'$(UseShiroBotSource)' == 'true'" />
        <PackageReference Include="ShiroBot.SDK" Condition="'$(UseShiroBotSource)' != 'true'" />
    </ItemGroup>

    <Import Project="$(ShiroBotSourceRoot)\SDK\buildTransitive\ShiroBot.SDK.targets"
            Condition="'$(UseShiroBotSource)' == 'true'" />

</Project>
